

const qaArray = [
    { question: "What is JSX?", answer: "JSX is a syntax extension for JavaScript, which looks similar to XML or HTML and is used with React to describe the UI." },
    { question: "How do you create a React component?", answer: "A React component can be created as a function or a class. Functional components use a simple function, whereas class components extend from React.Component." },
    { question: "What is a state in React?", answer: "State is a built-in object in React components used to store property values that belong to the component and can change over time." },
    { question: "What are props in React?", answer: "Props (short for properties) are read-only attributes passed from a parent component to a child component to configure or customize the child component." },
    { question: "What is the difference between state and props?", answer: "State is managed within the component and can change, while props are passed to the component from the parent and are read-only." },
    { question: "What is a hook in React?", answer: "Hooks are special functions in React that allow you to use state and other React features in functional components." },
    { question: "What is useState?", answer: "useState is a hook that allows you to add state to functional components in React." },
    { question: "How do you use useEffect?", answer: "useEffect is a hook that lets you perform side effects in functional components, such as fetching data or directly manipulating the DOM." },
    { question: "What is a key in React?", answer: "A key is a special string attribute you need to include when creating lists of elements in React to help identify which items have changed, are added, or removed." },
    { question: "What is the virtual DOM?", answer: "The virtual DOM is an in-memory representation of the real DOM elements generated by React components before updating the real DOM." },
    { question: "What is a higher-order component?", answer: "A higher-order component (HOC) is a function that takes a component and returns a new component, enhancing it with additional functionality." },
    { question: "How do you handle events in React?", answer: "Events in React are handled using camelCase syntax and passing event handlers as props to elements." },
    { question: "What is the purpose of React Router?", answer: "React Router is a library used to manage and handle navigation and routing in React applications." },
    { question: "What is the Context API?", answer: "The Context API is a React structure that enables you to exchange unique details and helps in solving prop-drilling from all levels of your application." },
    { question: "What is Redux?", answer: "Redux is a state management library for JavaScript apps, commonly used with React to manage the application state globally." },
    { question: "How do you connect Redux with React?", answer: "You connect Redux with React using the `connect` function from `react-redux` and the `Provider` component to wrap your app." },
    { question: "What is the use of refs in React?", answer: "Refs are used to access DOM elements or React elements created in the render method directly." },
    { question: "What is React.memo?", answer: "React.memo is a higher-order component that prevents a functional component from re-rendering if its props have not changed." },
    { question: "What is lazy loading in React?", answer: "Lazy loading in React is the technique of loading components only when they are needed, reducing the initial load time." },
    { question: "What is the useCallback hook?", answer: "useCallback is a React hook that returns a memoized version of the callback function that only changes if one of the dependencies has changed." }
  ];
  
  export default qaArray;